document.addEventListener(DOMContentLoaded, function(){
    const aumentaFonteBotao = document.getElementById('aumenta-fonte');

    let tamanhoAtualFonte = 1;

    aumentaFonteBotao.addEventListener('click', function() {
        tamanhoAtualFonte += 0.1;
        document.body.style.fontSize = `${tamanhoAtualFonte}
    }
    
    const diminuiFonteBotao = document.getElementById('diminui-fonte');
}